### PR TITLE
Add missing luatex and ptex primitives to l3names.dtx

### LINKED ISSUE #1248: missing luatex and ptex primitives from l3names.dtx
After seeing #1245 I decided to check if [`l3names.dtx`](https://github.com/latex3/latex3/blob/main/l3kernel/l3names.dtx) was missing any other primitives in the expl3 `\tex_<name>:D` form. From luatex I found it's missing
```tex
\boundary
\compoundhyphenmode
\deferred
\eTeXVersion % distinct from \eTeXversion
\eTeXminorversion
\exhyphenchar
\fixupboxesmode
\glet
\glyphdimensionsmode
\gtoksapp
\gtokspre
\mathflattenmode
\mathitalicsmode
\mathrulesmode
\mathrulethicknessmode
\protrusionboundary
\Uleft
\Umiddle
\Uright
\variablefam
\wordboundary
\xtoksapp
\xtokspre
```
and from ptex,
```tex
\ptexfontname
\ptextracingfonts
\tojis
```
I have no idea if `l3names.dtx` is attempting to have the complete list of available primitives. For example, I can see reasons for not having `\tex_glet:D`. If any or all of the list above should be added, I'm happy to make a PR (or leave it to y'all if that's easier).

### PR DESCRIPTION
**Pull request by mbertucci47**
Following #1245, adds several luatex and ptex primitives to `l3names.dtx`. Closes #1248.

### CODE REVIEW

**Comment by mbertucci47** [comment]
It's difficult to say which primitives should be excluded for being experimental. The only ones explicitly called experimental in the luatex manual are `\prebinoppenalty`, `\prerelpenalty`, and `\mathdelimitersmode`, and these were already present in `l3names.dtx` before this PR.

Some, namely `\compoundhyphenmode`, `\fixupboxesmode`, `\mathrulesmode`, and `\mathrulethicknessmode`, are not documented at all.

**Comment by FrankMittelbach** [comment]
> It's difficult to say which primitives should be excluded for being experimental. The only ones explicitly called experimental in the luatex manual are `\prebinoppenalty`, `\prerelpenalty`, and `\mathdelimitersmode`, and these were already present in `l3names.dtx` before this PR.
> 
> Some, namely `\compoundhyphenmode`, `\fixupboxesmode`, `\mathrulesmode`, and `\mathrulethicknessmode`, are not documented at all.

I guess I would add those too all but commented out with a note on the line `% not document in manual`. Then there is a reference in the file and one finds that at least.

**Comment by mbertucci47** [comment]
Done. I wasn't sure about the formatting as I tried to follow the chars/line of the file so feel free to comment

**Review by josephwright — APPROVED** [review]

**Comment by aminophen** [comment]
\ptexfontname and \ptextracinfgonts primitives are similar to \pdf... of pdfTeX but they include pTeX-specific information of Japaense fonts.

**Comment by FrankMittelbach** [comment]
> \ptexfontname and \ptextracinfgonts primitives are similar to \pdf... of pdfTeX but they include pTeX-specific information of Japaense fonts.

would that mean on could normalize on one name in expl3 and depending on the engine you just see a little more info? Or do the `\pdf...` exist in addition in the pTeX engines and it is worth/important to have both available?

**Comment by aminophen** [comment]
Sorry \ptexfontname output is quite different from \pdffontname one, so it would ne berrer to separate those.

**Pull request merged**
