### PR TITLE
Register prefix (prelim for prelim2e)

### PR DESCRIPTION
**Pull request by TeXhackse**
It's not a big package, but since this is to avoid duplicates, you get a registration. I hope you are fine with this, otherwise I can also stick to L2 Syntax for the internal macros.

### CODE REVIEW

**Comment by TeXhackse** [comment]
I didn't expect this to break something and the build system is confusing me. So if anyone could tell me if it's my fault, that would be great. Thank you. - I will wait with the CTAN upload for a reply here.

**Comment by PhelypeOleinik** [comment]
@TeXhackse No, the failure is due to font caching on Travis; not your fault :)

**Comment by FrankMittelbach** [comment]
I wonder if we can (and should) mask that out in the test if that could happen more often
```
! (load cache: extra_lmromanslant10-regular.luc)

! (load cache: ../extra_lmromanslant10-regular.lua.gz)(load cache: ../extra_lmromanslant10-regular.luc)
```
What do you think @josephwright ?  Doesn't seem to have sensible pattern hough.

**Comment by josephwright** [comment]
@FrankMittelbach  I did try but it's tricky, and a simple 're-run when the cache changes' approach _does_ work

**Pull request merged**
