### PR TITLE
Add variants of `\tl_if_eq:nn`

### PR DESCRIPTION
**Pull request by Stone-Zeng**
I think these functions maybe useful, for example, see https://tex.stackexchange.com/q/55600/136923.

By the way, why there is no `\tl_if_eq_p:nn`?

### CODE REVIEW

**Comment by josephwright** [comment]
I've no objection here, but most of the time the `str` comparison is more useful. Most notably, the string version is expandable: the `tl` version is not, hence the lack of a predicate version.

**Comment by eg9** [comment]
> On 24 Mar 2018, at 14:44 , Zeng Xiangdong <notifications@github.com> wrote:
> 
> I think these functions maybe useful, for example, see https://tex.stackexchange.com/q/55600/136923.

Variants can be added by the programmer as soon as need arises; the kernel provides several
prebuilt ones that appeared to be needed for applications. Others can be added when use cases
turn out to be interesting.

By using \cs_generate_variant:Nn one ensures that already existing variants are not clobbered
by user defined ones. Thus code using it will not do anything wrong if the generated variant is
later included in the kernel.

> By the way, why there is no \tl_if_eq_p:nn?

Because `\tl_if_eq:nnTF` cannot be expandable.

Ciao
Enrico

**Comment by wspr** [comment]
No complaints from me as long as we're consistent with the other variants we provide.

**Comment by FrankMittelbach** [comment]
The policy about variants (though not formally stated anywhere I think (maybe we should do that in interface3 somewhere)) is roughly like this:

 - there are a number of variants that we provide across the board with data structures to have a base set of commads available that are commonly used. For example we typically provide "c" and place of "N"

 - for anything else the idea is to provide a variant only if  there are at least a handful of independent use cases, otherwise the advice is to use \cs_generate_variant:Nn in the package or class file as there is nearly no overhead if at a later stage the variant is already provided by the kernel.

**Comment by blefloch** [comment]
It seems the consensus at least for now is to let programmers add variants themselves.

**Pull request closed without merging**
