### PR TITLE
l3str: fix a typo [ci skip]

### PR DESCRIPTION
**Pull request by Stone-Zeng**
Someone use `’` (U+2019) here. It should be `'` (U+0027).

So in the documentation, you will find something strange:
default

### CODE REVIEW

**Comment by josephwright** [comment]
There seem to be a lot of commits here for the one line that should change: could you tidy that up?

**Comment by Stone-Zeng** [comment]
Sorry, I'm not very familiar with git. Only the last commit (dee5115) is concerning this issue.

**Comment by josephwright** [comment]
@Stone-Zeng  I'll cherry-pick that one in a bit.

**Comment by josephwright** [comment]
I've cherry-picked the 'real' commit here: closing the PR.

**Pull request closed without merging**
