### PR TITLE
Add \bool_case:nTF in a branch

### PR DESCRIPTION
**Pull request by blefloch**
This family of four functions is requested by #530 (maybe I should have included that in the commit message).

But it adds one more candidate function when we are trying to get fewer of these.

### CODE REVIEW

**Comment by wspr** [comment]
Looks good to me. [ And no worries about discarding my old implementation :) ]

**Comment by eg9** [comment]
Seems good!

**Comment by wspr** [comment]
I forgot to mention also that although alternative names have been proposed, I’m happy with `bool_case` since there is a pretty clear similarity in behaviour / usage to the other `_case` functions.

**Comment by blefloch** [comment]
The main objector to this name was Frank, so maybe he has an opinion now?

**Comment by FrankMittelbach** [comment]
> The main objector to this name was Frank, so maybe he has an opinion now?

I guess I'm fine with it too, still think it is different from the other case functions but as @wspr said probably not that much to use a different name and anyway we never had a good suggestion for a name. So let's use this one.

**Comment by tail-reversion** [comment]
This is probably a useless note… The Lisp languages have a macro that works just like `\bool_case:n`, called `cond`.

**Comment by car222222** [comment]
I guess that a usage something like 
      \bool_case  \c_true_bool 
would make it into a faithful analogue of the other _case cases.

Which makes me think that, since booleans are both symmetric and binary in nature, we need these two cases:

   \bool_case_true   and     \bool_case_false 

The second will select the first false case: I agree that in this case the meaning of the T and F branches gets very very confusing!

An extension of this idea would be to allow a full analogy to the other cases by providing the more general

   \bool_case:nn  {<boolean expr>}  { list of  (boolean expressions ,  code) }

Which reminds me that it is important that all these case statements only use the code from the first match.  All subsequent matches are ignored.

**Comment by blefloch** [comment]
On 2/16/19 07:11, Chris Rowley wrote:
> I guess that a usage something like
> \bool_case \c_true_bool
> would make it into a faithful analogue of the other _case cases.
> 
> Which makes me think that, since booleans are both symmetric and binary
> in nature, we need these two cases:
> 
> \bool_case_true and \bool_case_false
> 
> The second will select the first false case: I agree that in this case
> the meaning of the T and F branches gets very very confusing!

I really like Chris' suggested name so I've implemented that, still in
the bool_case branch.  If we decide to use the names
\bool_case_true/false then the two commits on that branch should
probably be squashed to make all traces of \bool_case:n(TF) disappear.
For now I've kept both commits as we may still decide we prefer the name
\bool_case:nTF.

**Comment by josephwright** [comment]
Overall balance here seems to be positive: should I fix the conflicts and merge?

**Comment by wspr** [comment]
Yes, thanks — good for me.

**Comment by FrankMittelbach** [comment]
fine by me

**Pull request merged**
