### PR TITLE
Enable creation of new color models

### PR DESCRIPTION
**Pull request by josephwright**
For dealing with #740.

### CODE REVIEW

**Comment by josephwright** [comment]
One thing to think about here: do we want the family names to be case-sensitive. At present I've folded, but I'm not sure about `devicen` in place of `DeviceN` (`separation` vs `Separation` looks OK).

**Comment by josephwright** [comment]
@jbezos Have you ever needed `\pagecolorspace`, by the way: I'm not clear if we need that functionality.

**Comment by u-fischer** [comment]
@josephwright  I made a few tests last year and had the impression that one doesn't need it, imho there is somewhere even a comment and a test files about this in the pdfresource project, but I cant look now.

**Comment by car222222** [comment]
What commands \...colorspace (and \...color) are you providing so far?

**Comment by car222222** [comment]
My \\s got lost!

**Comment by jbezos** [comment]
> @jbezos Have you ever needed `\pagecolorspace`, by the way: I'm not clear if we need that functionality.

The main uses are covers and plates (see sec. 4 in the manual). Without `\pagecolorspace` you may need to prepare different PDF files for them, which can be cumbersome. These special pages are expected to be in the PDF at the correct places and with the correct color spaces.

**Comment by u-fischer** [comment]
@jbezos but what is a "correct colorspace " in this context? That it should contain the resources of the page is clear, but do additional resources from other pages harm?

**Comment by jbezos** [comment]
It tells the printer how each page must processed (very likely with different inks in a different press). I've personally never used it, because I have created no book covers, but I've come across several PDFs with a different color space.

**Comment by josephwright** [comment]
@jbezos  Perhaps I'm naive, but that sounds like a job normally done by making separate PDFs first, then combining them using a dedicated tool.

**Comment by u-fischer** [comment]
@jbezos the problem is that while it is possible (at least with pdflatex/lualatex) to create an individual ColorSpace resource for every page, it requires a certain amount of code  and enlarges the pdf. tikz/pgf has now for many years creates one ColorSpace object for all pages and I haven't seen a complaint about this, so I would for now not do it, unless I see a concrete example of a problem with it.

**Comment by jbezos** [comment]
Actually, two or three resources are enough (eg, body, book cover and plates), and once created they can be reused. Anyway, most prepress houses are used to deal with this, so I think it's not so essential and it can be left to an external package. This is one of the features I didn't manage to implement in `xetex`, and if “universality“ is a concern, this can be another reason to leave it out.

**Comment by car222222** [comment]
Below are some facts about the (very small amount of) stuff that is needed for color spaces in the pdf page resources, plus the single object that is needed to set up a color space (just once) for use in any way or any place in the pdf.  

In particular, within the pdf there is no need for anything such as a ‘page color space’.

These facts may not be relevant to this discussion.  If not, please can someone explain to me why concepts such as ‘page color space’ are needed, and how they are in any way related to the anything in the ‘pdf page resources’.   

I understand that, on the LaTeX side, whenever any ‘new color’ is set up for use in a document, there is a need to check whether the color space used to define the ‘new color’ has already been ‘defined in the pdf’ or is a ‘new color space’; and thus, if necessary, add an (indirect) array object and an internal name for the ‘new color space’.
Note that this is related only to the color spaces used by a color and has no relation to how that color is used.

Thus there is no such concept as the ‘the color space needed for all page colors’.

Finally, The Facts (AFAICT) About pdf named and color spaces:

1.  Each ColorSpace resource only sets up ‘local internal names’ for color spaces, these names are needed only for use in a page content stream or streams.

2.  These internal names are arbitrary and are not in any way related to the colors that use each color space or how/where that color is used.  They are not needed for the three standard Device... spaces.  They are simply pdf name objects that are needed because direct references are not allowed within content streams.

3.  Each such ‘named color space’ also needs a one-time (per document) definition as an indirect array object.  (Thus the only (possibly) significant amount of 'space in the pdf' that is needed is: one indirect array object per distinct color space that may (or may not) be used in the document.  There is no need to duplicate this array, even if it gets more than one internal name, since an object reference will be used within the page resource.)

4.  Thus the necessary number of ‘color space arrays’ is just one per color space and is in no way related to types/places of use of each color space.

**Comment by u-fischer** [comment]
@car222222  the question under discussion here is if we need page specific resource objects. If e.g. page one uses the color /color1 and /pattern1, and page two uses /color2, /shading1, /pattern2, there are two ways to sort the resources:

You can create a large object with the entries `<</color1 REF1 /color2 REF2 /pattern1 REF3 /shading1 REF4 /pattern2 REF4>>`  and reference this object in the ColorSpace resource of page 1 and page 2. 

Or you can create two object `<</color1 REF1 /pattern1 REF3>> ` and `<< /color2 REF2 shading1 REF4 /pattern2 REF5>>`  and reference the first object in the page resource of page one, and the second in the page resource of page two.

Currently both `pgf/tikz` and the resource management use method one. It is clearly easier to create: you simply collect all resources and dump then in one object. And gives less objects. The question is if there is a need to support method two.

**Comment by car222222** [comment]
@u-fischer Thanks, I understand now, and agree that your final question needs an answer.

FWIW, I cannot envisage a use-case that needs more than one such Colorspace name-dictionary.

**Pull request merged**
