### PR TITLE
Speed up `\tl_if_head_is_N_type:nTF`

### PR DESCRIPTION
**Pull request by Skillmon**
This speeds up `\tl_if_head_is_N_type:nTF` in most cases.

I benchmarked this in pdfTeX, LuaHBTeX, and XeTeX. Results are consistent for pdfTeX and XeTeX, but a bit off in LuaHBTeX. Tested cases were:

- empty argument: ca. 40% faster (5% in Lua)
- single space: ca. 39% faster (6% in Lua)
- single empty group: ca. 44% faster (16% in Lua)
- single `N`-type: ca. 40% faster (13% in Lua)
- single space followed by 10000 tokens: ca. 45% **slower** (same for Lua)
- single group containing 10000 tokens: ca. 5% faster (13% in Lua)
- `N`-type followed by 10000 tokens: ca. 24% faster (34% in Lua)

So except for one test case this is considerably faster. I didn't check for how many tokens following a space the old implementation takes the lead.

### CODE REVIEW

**Comment by josephwright** [comment]
Looks good to me but let's see if @blefloch has time to cast his eye over it. I assume the test coverage looks OK here?

**Comment by Skillmon** [comment]
In pdfTeX the results are consistent (20% - 30% speed up for 100 - 10000 replications), in LuaTeX they are indeed slower, the new code takes roughly twice as long for 100 - 10000 replications.

**Comment by Skillmon** [comment]
We could implement the new code for pdfTeX and XeTeX, and the old code for LuaTeX -- if diverging is fine by the team of course.

**Comment by zauguin** [comment]
@Skillmon Do you have some benchmarking code for this?

**Comment by Skillmon** [comment]
@zauguin sorry, didn't see your message. I guess in the meantime you wrote it yourself, but you can find the stuff I usually use for benchmarks here: https://topanswers.xyz/tex?q=2096

**Pull request closed without merging**
