### PR TITLE
Correct the definition of \l_char_active_seq

### PR DESCRIPTION
**Pull request by qinglee**

### CODE REVIEW

**Comment by wspr** [comment]
thanks!

**Comment by josephwright** [comment]
@wspr Remember you need to merge using a local Git checkout, rebase then push :) I've tidied up!

**Comment by wspr** [comment]
@josephwright Oh dear, thanks for the reminder :)

**Comment by josephwright** [comment]
@wspr  Well, you can merge in GitHub, but you still need to pull locally and rebase ...

**Comment by josephwright** [comment]
@qinglee  Thanks as usual for the careful reading

**Pull request merged**
