### PR TITLE
Newprefixes

### PR DESCRIPTION
**Pull request by u-fischer**

### CODE REVIEW

**Comment by u-fischer** [comment]
I'm not sure to which "packages" the latex2e prefixes actually belong (and which date to use ...)

**Comment by FrankMittelbach** [comment]
maybe we should make a global change here and change LaTeX3 Project to LaTeX Project in the file.

**Comment by PhelypeOleinik** [comment]
It's missing the `hook` prefix from `lthooks`.  I think that as “package” the file name is okay (for example `lthooks` introduces itself as “The `lthooks` package”), but it might be confusing... Maybe “LaTeX2e - `lthooks`”?

**Comment by FrankMittelbach** [comment]
or maybe just "LaTeX format"  for all those that are inside the format?

**Comment by car222222** [comment]
@u-fischer I guess there is some reason not to use 'hyper'?
'hyp' looks a bit strange to me, but better than hype:-)!

**Comment by u-fischer** [comment]
@car222222  no real reason, mostly because I thought three letters are enough. hyperref itself use `\Hy` as prefix, sometimes with some additions like `\HyPsd`, but I didn't want to use uppercase, and hy looked to much like a greeting. But perhaps it would be really better to use `hyper`.

**Pull request merged**
