### PR TITLE
 Corrected a typo: command -> common

### PR DESCRIPTION
**Pull request by EvanAad**
Also: Rephrased a clause for correct grammar.

### CODE REVIEW

**Comment by josephwright** [comment]
I'll cherry-pick the two 'real' commits here to avoid the merges (saves your rebasing).

**Comment by josephwright** [comment]
Merged in so closing.

**Comment by josephwright** [comment]
Actually, the 'distinct' one was already done yesterday!

**Comment by EvanAad** [comment]
I have very little experience using Git. I may be doing things not
quite right. My workflow is this:

1. git pull upstream master (this sometimes results in a commit)
2. FIX BUG
3. git pull upstream master (this sometimes results in a commit)
4. If the previous step didn't result in a commit: git commit -m <message>
5. git push origin master
6. I open GitHub in my browser and hit the "Pull request" button.

If this is not a good workflow, please let me know.

**Comment by josephwright** [comment]
@EvanAad  In the end it's not a big issue as I 'tidy up' when merging. However, probably the way that fits best with our aim of a linear history is

1. Update your main checkout: `git pull upstream master`
2. Create a branch for what you are doing: `git checkout -b <name>`
3. Fix stuff
4. Commit
5. Push and create pull request

If you pull the `upstream` version after your commit you might end up with a merge. You can sort that by rebasing (`git rebase upstream master`) but if you just avoid pulling after making your changes then I can rebase as part of merging a pull request.

**Comment by josephwright** [comment]
BTW, the reason for suggesting creating a branch for each pull request is that this fits with how GitHub works. GitHub automatically adds new commits to a branch to any pull request from that branch, so if you are doing different things then can get 'mixed up' if you have them all in `master`.

**Comment by EvanAad** [comment]
OK, thanks.

**Comment by blefloch** [comment]
From your last pull request it seems there's still a problem with stray commits.
@josephwright do you know how @EvanAad could clean up their master branch https://github.com/EvanAad/latex3/tree/master so that it is not "7 commits ahead of latex3/latex3"?

**Comment by josephwright** [comment]
@blefloch I guess that @EvanAad has made changes on his `master` branch and so they are 'appearing' in every branch/pull request. The best plan is to get the `master` branch back on track with ours, which I think comes down to `git reset --hard upstream master` or similar.

**Comment by EvanAad** [comment]
I can delete my Git repository and clone/refork it from scratch. Will this help?

**Comment by josephwright** [comment]
@EvanAad Yup, that will sort it :) As I've said elsewhere, 'safest' is to make changes for pull request on a branch. [It's different of course when one has commit access to the repo: the team favour a simple 'all on `master` workflow, but we keep it linear and most of the team use SVN anyway :)]

**Comment by EvanAad** [comment]
Each of the last two pull requests I've submitted were done on a branch.

**Comment by josephwright** [comment]
@EvanAad Sure, but as I said before I think you'd got your `master` branch out-of-sync with our one, which is where the merge commits were appearing from. For a fork, the only way I'd change `master` is pulling from upstream. (Note: the team mainly use SVN so our experience with Git workflows is quite limited!)

**Pull request closed without merging**
