### PR TITLE
[xparse] Define a set of validators

### PR DESCRIPTION
**Pull request by hmenke**
Alternative approach at #373.

The regexes for floats and dimensions might look a little weird, but in fact `.pt` is a valid dimension in TeX (and thus `.` is a valid floating point literal as well).
```latex
\dimen0=.pt
\the\dimen0 % 0.0pt
```

### CODE REVIEW

**Comment by eg9** [comment]
An integer in TeX can also be in octal, hexadecimal or alphabetic format.

**Comment by josephwright** [comment]
@eg9  True, but at the interface level one is free to define whatever one wants. I might be tempted to consider `\afterassignment` here and check for 'residue', if the aim is to see 'Will TeX parse fully as an integer'.

**Comment by blefloch** [comment]
While the code probably works, the processors ought to set `\ProcessedArgument` I believe.  Perhaps it would be better to use `\regex_extract_once:nnN {#1} { ^([+-\ ]*\d+\ *)(.*)$` }` into some seq, then check the number of items and store just the integer in `\ProcessedArgument`.  Hopefully I got the regex right, allowing more spaces and an arbitrary number of signs.

If people think it's useful I could probably adapt the `l3fp` parser to provide a function to "parse until failure" and return the split token list, the result, and true/false.  It could have an `int`, `dim`, `skip`, `fp` variants.

**Comment by hmenke** [comment]
@eg9 My intended purpose of these macros is not to check whether the argument is a valid TeX integer, but a valid integer literal, i.e. an optional sign and one or more digits.  This brings me to the suggestions by @blefloch.  The regex  `^([+-\ ]*\d+\ *)(.*)$` seems weird to me.  Why would you allow multiple signs?  Furthermore, since this is not a real processor but a validator, it leaves the argument unaltered if it is valid and throws an error otherwise.  Is setting `\ProcessedArgument` required in that case as well?

**Comment by blefloch** [comment]
Yes, while xparse's implementation details currently let you not set the `\ProcessedArgument` when it's not changed, that may very well change in the future (since it's not documented behaviour) so it's safer to stick to the documented interface namely set the `\ProcessedArgument` in all cases.

About signs, it really depends on what applications you have in mind, but I wouldn't be surprised if such double signs show up after a few indirections (user defines a command in terms of the package's command) where at various stages one may want to put a sign.

**Comment by josephwright** [comment]
I do plan to take this: we have some internal changes to make first ...

**Comment by josephwright** [comment]
At the moment I don't think this is going to progress, but we should look again at the idea.

**Pull request closed without merging**
