### PR TITLE
Fix various misspelling

### PR DESCRIPTION
**Pull request by muzimuzhi**
Found with `codespell -L 'alph,co-ordinate,co-ordinates,filetest,inteval,openin' -S './texmf,*.eps,*.tlg'`.

### CODE REVIEW

**Comment by josephwright** [comment]
Please exclude `xpackages`: this is all frozen stuff we really don't want to change

**Comment by car222222** [comment]
Good stuff! 
Useful automation finally hits the documentation:-).

**Comment by josephwright** [comment]
Nice tool - have just set it up

**Comment by car222222** [comment]
What horrors did you find in siunitx:-)

**Comment by car222222** [comment]
So little, congratulations!
I like "hightlight", you should have kept that:-).

**Comment by muzimuzhi** [comment]
> Useful automation finally hits the documentation:-).

Got to know `codespell` for the first time in https://github.com/CTeX-org/zhlipsum/pull/8.

**Comment by muzimuzhi** [comment]
Need to reduce false positive matches.

**Comment by josephwright** [comment]
> Need to reduce false positive matches.

I was thinking for changed lines -we would then have an exclusions list that went with the repo as a whole, which would be added to be commits with 'odd' spellings

**Comment by josephwright** [comment]
There is a Codespell action: only works on PRs at the moment - may be worth trying out

**Pull request merged**
