### PR TITLE
Speed up string comparison by using \if

### PR DESCRIPTION
**Pull request by Skillmon**
The `\pdfstrcmp` primitive (and equivalent implementations, including the current Lua code used by `expl3` in LuaTeX) doesn't return its result as a count register or similar, but as a tokens of category 12. It is therefore faster to check whether the result is equal to `0` by using the `\if` primitive instead of `\ifnum` (my benchmarks indicate 10% speed difference for the check in pdfTeX).

This changes those usages of `\pdfstrcmp` in which the result is only tested to be equal to zero to use `\if`.

### CODE REVIEW

**Review by FrankMittelbach — CHANGES_REQUESTED** [review]
Imo that kind of change should be documented with short note giving the reason, otherwise it will later be incomprehensible (or changed back by mistake as the speed gain is not necessarily obvious).

**Comment by Skillmon** [comment]
The failing checks aren't my fault, I got "lucky" again with the midyear deprecations.

**Comment by Skillmon** [comment]
Just a prod: How does it look now?

**Review by FrankMittelbach — APPROVED** [review]
can't see anything wrong with that but by the end of the day it is @blefloch  who needs to decide and he unavailable during August.

**Comment by Skillmon** [comment]
@FrankMittelbach ok, thanks for taking the time!

**Pull request merged**
